[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
crud = "H3LQQdXCGzkbMXGa5hBxASiP3iBipZFX3qbJwybEbeXZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/wallets/phantom-devnet.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"
